version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.17.6

aliases:
  - &install_npm_dependencies
    name: Installing NPM Dependencies
    command: npm ci

commands:
  setup_git:
    steps:
      - add_ssh_keys:
          fingerprints:
            - '85:6e:5d:a6:3b:97:82:a2:6b:de:20:67:1f:f8:ba:d0'
      - run:
          name: Setup git config global
          command: |
            git config user.email "dev@codetot.com"
            git config user.name "CODE TOT JSC"

jobs:
  test_code:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: *install_npm_dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build_assets:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: *install_npm_dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - attach_workspace:
          at: ~/repo
      - run:
          command: npm run build
      - setup_git
      - run:
          name: Commit changes
          command: |
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit -m "Process styles and scripts [skip ci]"
              git push origin HEAD:${CIRCLE_BRANCH}
              exit 0
            else
              exit 0
            fi
      - persist_to_workspace:
          root: ~/repo
          paths: .
  release_production:
    <<: *defaults
    steps:
      - checkout
      - setup_git
      - run:
          name: Remove source
          command: |
              rm -rf assets/js/*.js.LICENSE.txt src/
              rm -rf .babelrc .browserslistrc .eslintrc.js .prettierignore .stylelintrc
              rm -rf components/*/src/ components/*/src/package*.json components/*/src/.gitignore components/*/src/.stylelintignore components/*/src/.stylelintrc.json components/*/src/.prettierignore
      - run:
          name: Commit changes
          command: |
              git add .
              git commit -m "Prepare production package"
              git push origin HEAD:production-temp --force
              git reset --hard origin/production
              git merge origin/production-temp --no-ff --no-edit -m "Release package"
              git push origin HEAD:production
              git push origin :production-temp

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_code:
          filters:
            branches:
              only: /(feature|bugfix|hotfix)\/?(.*)/
      - build_assets:
          filters:
            branches:
              only: /(develop|feature\/ci)/
      - release_production:
          filters:
            branches:
              only: master
