version: 2.1

orbs:
  node: circleci/node@4.7.0

aliases:
  - &restore_npm_cache
    name: 'Restoring node_modules from the cache'
    key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
  - &install_npm_dependencies
    name: Installing NPM Dependencies
    command: npm ci
  - &save_npm_cache
    name: 'Saving node_modules into the cache'
    key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
    paths:
      - node_modules

commands:
  setup_git:
    steps:
      - add_ssh_keys:
          fingerprints:
            - '85:6e:5d:a6:3b:97:82:a2:6b:de:20:67:1f:f8:ba:d0'
      - run:
          name: Setup git config global
          command: |
            git config user.email "dev@codetot.com"
            git config user.name "CODE TOT JSC"

  setup_npm:
    working_directory: ~/example
    steps:
      - restore_cache: *restore_npm_cache
      - run: *install_npm_dependencies
      - save_cache: *save_npm_cache
      - persist_to_workspace:
          root: ~/example
          paths:
            - node_modules

  test_code:
    working_directory: ~/example
    executor: node/default
    steps:
      - checkout:
          path: ~/example
      - setup_npm
      - attach_workspace:
          at: ~/example
      - run:
          command: npm run test

  build_assets:
    working_directory: ~/example
    executor: node/default
    steps:
      - checkout:
          path: ~/example
      - setup_npm
      - attach_workspace:
          at: ~/example
      - run:
          command: npm run build
      - setup_git
      - run:
          name: Commit changes
          command: |
              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit -m "Process styles and scripts [skip ci]"
                git push origin HEAD:${CIRCLE_BRANCH}
                exit 0
              else
                exit 0
              fi

  release_production:
    executor: node/default
    steps:
      - checkout
      - setup_git
      - run:
          name: Remove source
          command: |
              rm -rf assets/js/*.js.LICENSE.txt src/
              rm -rf .babelrc .browserslistrc .eslintrc.js .prettierignore .stylelintrc
              rm -rf components/*/src/ components/*/src/package*.json components/*/src/.gitignore components/*/src/.stylelintignore components/*/src/.stylelintrc.json components/*/src/.prettierignore
      - run:
          name: Commit changes
          command: |
              git add .
              git commit -m "Prepare production package"
              git push origin HEAD:production-temp --force
              git reset --hard origin/production
              git merge origin/production-temp --no-ff --no-edit -m "Release package"
              git push origin HEAD:production
              git push origin :production-temp

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_code:
          filters:
            branches:
              only: /(feature|bugfix|hotfix)\/?(.*)/
      - build_assets:
          filters:
            branches:
              only: /(develop|feature\/ci)/
      - release_production:
          filters:
            branches:
              only: master
